export const SIGNUP_ACTION = "[action] signup user";
export const SET_USER_TOKEN_DATA_MUTATION = "[mutation] set user token";
export const LOADING_SPINNER_SHOW_MUTATION = "[mutation] show loading spinner";
export const LOGIN_ACTION = "[action] login user";
export const LOGOUT_ACTION = "[action] logout user";
export const AUTH_LOGIN_ACTION = "[action] Auth auto login"
export const AUTH_ACTION = "[action] Do User Auth";
export const GET_USER_TOKEN_GETTER = "[getters] auth user token";
export const IS_USER_AUTHENTICATE_GETTER = "[getters] is user authenticated"
